stages:
  - build
  - run

Build:
  stage: build
  script:
    - echo VITE_API_URL=/api > .env.local
    - docker-compose -f ./ci/docker-compose.yml build --no-cache --remove-orphans
  tags:
    - tablo
#  only:
#    - master
Run:
  stage: run
  script:
    - docker-compose -f ./ci/docker-compose.yml up -d
  tags:
    - tablo
#  only:
#    - master
