stages:
  - build
  - run

Build:
  stage: build
  script:
    - docker-compose -f ./ci/docker-compose.yml build --no-cache
  tags:
    - rnr
#  only:
#    - master
Run:
  stage: run
  script:
    - docker-compose -f ./ci/docker-compose.yml up -d
  tags:
    - rnr
#  only:
#    - master
