version: "3"
services:
  scoreboard:
    restart: always
    build:
      context: ../
      dockerfile: ./ci/Dockerfile
    working_dir: /srv/app
    stdin_open: true
    ports:
      - '${DOCKER_PORT}:80'
